
export const GET_CLASSES = 'GET_CLASSES';
export const GET_CLASSES_ERROR = 'GET_CLASSES_ERROR';
export const GET_CLASSES_FAILURE = 'GET_CLASSES_FAILURE';
export const ADD_CUSTOMER_COMPLETE = 'ADD_CUSTOMER_COMPLETE';
export const ADD_CUSTOMER_ERROR = 'ADD_CUSTOMER_ERROR';
export const ADD_CUSTOMER_FAILURE = 'ADD_CUSTOMER_FAILURE';
export const UPDATE_CUSTOMER_COMPLETE = 'UPDATE_CUSTOMER_COMPLETE';
export const UPDATE_CUSTOMER_ERROR = 'UPDATE_CUSTOMER_ERROR';
export const UPDATE_CUSTOMER_FAILURE = 'UPDATE_CUSTOMER_FAILURE';
export const FETCH_CUSTOMER_COMPLETE = 'FETCH_CUSTOMER_COMPLETE';
export const FETCH_CUSTOMER_ERROR = 'FETCH_CUSTOMER_ERROR';
export const FETCH_CUSTOMER_FAILURE = 'FETCH_CUSTOMER_FAILURE';
export const FETCH_CUSTOMERBYID_COMPLETE = 'FETCH_CUSTOMERBYID_COMPLETE';
export const FETCH_CUSTOMERBYID_ERROR = 'FETCH_CUSTOMERBYID_ERROR';
export const FETCH_CUSTOMERBYID_FAILURE = 'FETCH_CUSTOMERBYID_FAILURE';
export const START_SPINNER_ACTION = 'START_SPINNER_ACTION';
export const STOP_SPINNER_ACTION = 'STOP_SPINNER_ACTION';
export const LOGIN_COMPLETE = 'LOGIN_COMPLETE';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SHOW_SNACKBAR_ACTION = 'SHOW_SNACKBAR_ACTION';
export const HIDE_SNACKBAR_ACTION = 'HIDE_SNACKBAR_ACTION';
export const API = 'API';
export const SET_TOKEN = 'SET_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';

